// File generated by FlutterFire CLI (`flutterfire configure`).
// ignore_for_file: type=lint
//
// Linked to Firebase project `altamayuz-web`. This app shares the SAME
// Firebase project as admin_app/ so the storefront's `products` reads and
// submitPublicOrder calls reach the same Firestore database and Cloud
// Functions. Re-run `flutterfire configure` to regenerate.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform. '
      'Run `flutterfire configure` to add it.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5XEllbkMk_o0pY-2ENs1zbWZZHP-u9Og',
    appId: '1:1076327409181:web:8d49aaa61e5fe3ff3888f4',
    messagingSenderId: '1076327409181',
    projectId: 'altamayuz-web',
    authDomain: 'altamayuz-web.firebaseapp.com',
    storageBucket: 'altamayuz-web.firebasestorage.app',
    measurementId: 'G-GYZ7MPYHTZ',
  );
}
